name: MacOS Build Test

on: [push]

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup Env
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install wheel
    - name: Build
      shell: bash -l {0}
      run: |
          python setup.py bdist_wheel
